version: 0.2

phases:
  install:
    commands:
      - echo installing...
      - apt install zip
      - npm install
  pre_build:
    commands:
      - echo testing...
      - npx jest
  build:
    commands:
      - echo building...
      - zip -r brotli-request.zip lambda/brotli-request/
      - npm run build
  post_build:
    commands:
      - echo deploying...
      - aws lambda update-function-code
        --function-name  brotli-request
        --zip-file fileb://lambda/brotli-request.zip
      - aws s3 cp dist/index.html $BUCKET
      - aws s3 cp dist $BUCKET
        --recursive
        --content-encoding "br"
        --content-type "text/javascript"
        --exclude "*"
        --include "*.br"