version: 0.2

phases:
  install:
    commands:
      - echo installing packages...
      - apt install zip
      - npm install
  pre_build:
    commands:
      - echo running tests...
      - npx jest
  build:
    commands:
      - echo building...
      - npm run build
  post_build:
    commands:
      - aws s3 cp dist/index.html $BUCKET
      - aws s3 cp dist $BUCKET
        --recursive
        --content-encoding "br"
        --content-type "text/javascript"
        --exclude "*"
        --include "*.br"