name: CI
on:
  push:
    branches: [ master ]
jobs:
  codecommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pushes to codecommit
        run: |
          git config --global user.name ${{ secrets.CODECOMMIT_USER }}
          git config --global user.password ${{ secrets.CODECOMMIT_PASSWORD }}
          git remote add codecommit ${{ secrets.CODECOMMIT_URL }}
          git push codecommit master
