name: CI
on:
  push:
    branches: [ master ]
jobs:
  codecommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pushes to codecommit
        run: |
          git remote add origin ${{ secrets.CODECOMMIT_URL }}
          git push origin master
