name: CI
on:
  push:
    branches: [ master ]
jobs:
  codecommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pushes to codecommit
        run: |
          mkdir .ssh && cd .ssh && echo "$SSH_PRIVATE_KEY" > id_rsa && chmod 600 id_rsa
          echo "$(ls -a)"
          cat id_rsa
          echo "$SSH_CONFIG" > config && chmod 600 config && cd ..
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          echo "$(ls .ssh -a)"
          git remote add codecommit "$CODECOMMIT_URL"
          git push codecommit master --force
          echo "$(ls -a)"
        shell: bash
        env:
          CODECOMMIT_URL: ${{ secrets.CODECOMMIT_URL }}
          SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # SSH_USERNAME: ${{ secrets.SSH_USERNAME }}


        # echo "$(ssh -i id_rsa -o StrictHostKeyChecking=no -l $SSH_USERNAME)"
        # echo "$SSH_CONFIG" > config && chmod 600 config && cd ..
        # echo "$(ls .ssh -a)"
        # echo "$(cat .ssh/id_rsa)"
        # echo ${{ secrets.GIT_CREDENTIALS }} > git-credentials.txt
        # git config --global credential.helper 'store --file git-credentials.txt'
        # git remote add codecommit ${{ secrets.CODECOMMIT_URL }}
        # git push codecommit master
        # echo "$(ls)"
        # run: |
        #   'echo "$GIT_CREDENTIALS" > .git-credentials'
        #   cat .git-credentials
        #   git config --global credential.helper 'store --file .git-credentials'
        #   git remote add codecommit "$CODECOMMIT_URL"
        #   git push codecommit master
        # shell: bash
        #   GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
        #   CODECOMMIT_URL: ${{ secrets.CODECOMMIT_URL }}
