name: CI
on:
  push:
    branches: [ master ]
jobs:
  codecommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pushes to codecommit
        run: |
          echo ${{ secrets.GIT_CREDENTIALS }} > ./.git-credentials
          git config --global credential.helper 'store --file ./.git-credentials'
          git remote add codecommit ${{ secrets.CODECOMMIT_URL }}
          git push codecommit master
