name: CI
on:
  push:
    branches: [ master ]
jobs:
  codecommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pushes to codecommit
        run: |
          echo ${{ secrets.GIT_CREDENTIALS }} > git-credentials.txt
          git config --global credential.helper 'store --file git-credentials.txt'
          git remote add codecommit ${{ secrets.CODECOMMIT_URL }}
          git push codecommit master
        # echo "$(ls)"
        # run: |
        #   'echo "$GIT_CREDENTIALS" > .git-credentials'
        #   cat .git-credentials
        #   git config --global credential.helper 'store --file .git-credentials'
        #   git remote add codecommit "$CODECOMMIT_URL"
        #   git push codecommit master
        # shell: bash
        # env:
        #   GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
        #   CODECOMMIT_URL: ${{ secrets.CODECOMMIT_URL }}
